### ISSUE TITLE
should be env var aware

### ISSUE THREAD

**Issue by AlexJeffcott** [AlexJeffcott/shuhari#6]
Code should be able to access environment variables.
For example, the programme should know whether `NODE_ENV === 'production'`

**Comment by ararita** [comment]
Hey @AlexJeffcott could you please provide some details on this issue? I'm not clear what exactly is the requirement here

**Comment by AlexJeffcott** [comment]
I updated the description, does that answer your question or shall we talk about it?

**Comment by ararita** [comment]
> I updated the description, does that answer your question or shall we talk about it?
> 
> I would take a look at what the carreers repo does (timo usually takes a particular which you could use as the jumping off point).

I still don't know what I should do. I understand what should be the outcome, but not what are exactly steps I need to take. I did look into the careers repo, but that didn't help

**Comment by ararita** [comment]
PR: https://github.com/AlexJeffcott/shuhari/pull/17
